# - hosts: all
#   connection: local
#   remote_user: root
#   become_user: root
#   become: true
#   tasks:
---
  # Typora
  - name: Verify and add the Typora package signing key
    ansible.builtin.apt_key:
      id: BA300B7755AFCFAE
      state: present
      url: https://typora.io/linux/public-key.asc
      validate_certs: true

  - name: Add Typora deb repository
    ansible.builtin.apt_repository:
      repo: deb https://typora.io/linux ./
      state: present
      update_cache: true
      validate_certs: true

  - name: Install the latest version of Typora
    ansible.builtin.apt:
      pkg:
        - typora
      state: present
      update_cache: true

  # VSCode
  - name: Ensure apt uses https
    ansible.builtin.apt:
      pkg:
        - apt-transport-https
      state: present
      update_cache: true

  - name: Verify and add the Microsoft package signing key
    ansible.builtin.apt_key:
      id: EB3E94ADBE1229CF
      keyring: /etc/apt/keyrings/packages.microsoft.gpg
      state: present
      url: https://packages.microsoft.com/keys/microsoft.asc
      validate_certs: true

  # - name: Add Visual Studio Code deb repository
  #   ansible.builtin.apt_repository:
  #     repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
  #     state: present
  #     filename: vscode
  #     update_cache: true
  #     validate_certs: true
  - name: Add Visual Studio Code deb repository
    become: yes
    become_user: root
    shell: echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list

  - name: Install the latest version of Visual Studio Code
    ansible.builtin.apt:
      pkg:
        - code
      state: present
      update_cache: true

  # ATuin
  # - name: Install the Atuin
  #   become_user: vagrant
  #   shell: curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh
